const express = require("express");
const app = express();
const PORT = process.env.PORT || 3000;

// Area Code and Timezone Mapping
const timezoneMap = {
  201: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  202: {
    timezone: "America/New_York",
    offset: "EST",
    region: "District of Columbia",
  },
  203: { timezone: "America/New_York", offset: "EST", region: "Connecticut" },
  204: { timezone: "America/Winnipeg", offset: "CEN", region: "Manitoba" },
  205: { timezone: "America/Chicago", offset: "CEN", region: "Alabama" },
  206: { timezone: "America/Los_Angeles", offset: "PAC", region: "Washington" },
  207: { timezone: "America/New_York", offset: "EST", region: "Maine" },
  208: { timezone: "America/Boise", offset: "MTN", region: "Idaho" },
  209: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  210: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  212: { timezone: "America/New_York", offset: "EST", region: "New York" },
  213: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  214: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  215: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  216: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  217: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  218: { timezone: "America/Chicago", offset: "CEN", region: "Minnesota" },
  219: { timezone: "America/Chicago", offset: "CEN", region: "Indiana" },
  220: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  223: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  224: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  225: { timezone: "America/Chicago", offset: "CEN", region: "Louisiana" },
  226: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  228: { timezone: "America/Chicago", offset: "CEN", region: "Mississippi" },
  229: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  231: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  234: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  236: {
    timezone: "America/Vancouver",
    offset: "PAC",
    region: "British Columbia",
  },
  239: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  240: { timezone: "America/New_York", offset: "EST", region: "Maryland" },
  248: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  249: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  250: {
    timezone: "America/Vancouver",
    offset: "PAC",
    region: "British Columbia",
  },
  251: { timezone: "America/Chicago", offset: "CEN", region: "Alabama" },
  252: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  253: { timezone: "America/Los_Angeles", offset: "PAC", region: "Washington" },
  254: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  256: { timezone: "America/Chicago", offset: "CEN", region: "Alabama" },
  260: {
    timezone: "America/Indiana/Indianapolis",
    offset: "EST",
    region: "Indiana",
  },
  262: { timezone: "America/Chicago", offset: "CEN", region: "Wisconsin" },
  267: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  269: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  270: { timezone: "America/Chicago", offset: "CEN", region: "Kentucky" },
  272: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  276: { timezone: "America/New_York", offset: "EST", region: "Virginia" },
  279: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  281: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  289: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  301: { timezone: "America/New_York", offset: "EST", region: "Maryland" },
  302: { timezone: "America/New_York", offset: "EST", region: "Delaware" },
  304: { timezone: "America/New_York", offset: "EST", region: "West Virginia" },
  305: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  306: { timezone: "America/Regina", offset: "MTN", region: "Saskatchewan" },
  307: { timezone: "America/Denver", offset: "MTN", region: "Wyoming" },
  308: { timezone: "America/Chicago", offset: "CEN", region: "Nebraska" },
  309: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  310: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  312: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  313: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  314: { timezone: "America/Chicago", offset: "CEN", region: "Missouri" },
  315: { timezone: "America/New_York", offset: "EST", region: "New York" },
  316: { timezone: "America/Chicago", offset: "CEN", region: "Kansas" },
  317: {
    timezone: "America/Indiana/Indianapolis",
    offset: "EST",
    region: "Indiana",
  },
  318: { timezone: "America/Chicago", offset: "CEN", region: "Louisiana" },
  319: { timezone: "America/Chicago", offset: "CEN", region: "Iowa" },
  320: { timezone: "America/Chicago", offset: "CEN", region: "Minnesota" },
  321: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  323: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  325: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  326: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  330: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  331: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  332: { timezone: "America/New_York", offset: "EST", region: "New York" },
  334: { timezone: "America/Chicago", offset: "CEN", region: "Alabama" },
  336: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  337: { timezone: "America/Chicago", offset: "CEN", region: "Louisiana" },
  339: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  341: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  343: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  346: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  347: { timezone: "America/New_York", offset: "EST", region: "New York" },
  351: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  352: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  360: { timezone: "America/Los_Angeles", offset: "PAC", region: "Washington" },
  361: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  364: { timezone: "America/Chicago", offset: "CEN", region: "Kentucky" },
  365: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  367: { timezone: "America/Montreal", offset: "EST", region: "Quebec" },
  380: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  385: { timezone: "America/Denver", offset: "MTN", region: "Utah" },
  386: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  401: { timezone: "America/New_York", offset: "EST", region: "Rhode Island" },
  402: { timezone: "America/Chicago", offset: "CEN", region: "Nebraska" },
  403: { timezone: "America/Calgary", offset: "MTN", region: "Alberta" },
  404: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  405: { timezone: "America/Chicago", offset: "CEN", region: "Oklahoma" },
  406: { timezone: "America/Denver", offset: "MTN", region: "Montana" },
  407: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  408: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  409: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  410: { timezone: "America/New_York", offset: "EST", region: "Maryland" },
  412: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  413: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  414: { timezone: "America/Chicago", offset: "CEN", region: "Wisconsin" },
  415: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  416: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  417: { timezone: "America/Chicago", offset: "CEN", region: "Missouri" },
  423: { timezone: "America/New_York", offset: "EST", region: "Tennessee" },
  424: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  425: { timezone: "America/Los_Angeles", offset: "PAC", region: "Washington" },
  430: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  431: { timezone: "America/Winnipeg", offset: "CEN", region: "Manitoba" },
  432: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  434: { timezone: "America/New_York", offset: "EST", region: "Virginia" },
  443: { timezone: "America/New_York", offset: "EST", region: "Maryland" },
  445: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  450: { timezone: "America/Montreal", offset: "EST", region: "Quebec" },
  458: { timezone: "America/Los_Angeles", offset: "PAC", region: "Oregon" },
  463: {
    timezone: "America/Indiana/Indianapolis",
    offset: "EST",
    region: "Indiana",
  },
  469: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  470: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  475: { timezone: "America/New_York", offset: "EST", region: "Connecticut" },
  478: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  479: { timezone: "America/Chicago", offset: "CEN", region: "Arkansas" },
  480: { timezone: "America/Phoenix", offset: "MTN", region: "Arizona" },
  484: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  501: { timezone: "America/Chicago", offset: "CEN", region: "Arkansas" },
  502: { timezone: "America/Louisville", offset: "EST", region: "Kentucky" },
  503: { timezone: "America/Los_Angeles", offset: "PAC", region: "Oregon" },
  504: { timezone: "America/Chicago", offset: "CEN", region: "Louisiana" },
  505: { timezone: "America/Denver", offset: "MTN", region: "New Mexico" },
  506: { timezone: "America/Moncton", offset: "ATL", region: "New Brunswick" },
  507: { timezone: "America/Chicago", offset: "CEN", region: "Minnesota" },
  508: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  509: { timezone: "America/Los_Angeles", offset: "PAC", region: "Washington" },
  510: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  512: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  513: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  514: { timezone: "America/Montreal", offset: "EST", region: "Quebec" },
  515: { timezone: "America/Chicago", offset: "CEN", region: "Iowa" },
  516: { timezone: "America/New_York", offset: "EST", region: "New York" },
  517: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  518: { timezone: "America/New_York", offset: "EST", region: "New York" },
  519: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  520: { timezone: "America/Phoenix", offset: "MTN", region: "Arizona" },
  559: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  561: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  562: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  563: { timezone: "America/Chicago", offset: "CEN", region: "Iowa" },
  564: { timezone: "America/Los_Angeles", offset: "PAC", region: "Washington" },
  567: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  570: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  571: { timezone: "America/New_York", offset: "EST", region: "Virginia" },
  573: { timezone: "America/Chicago", offset: "CEN", region: "Missouri" },
  574: {
    timezone: "America/Indiana/Indianapolis",
    offset: "EST",
    region: "Indiana",
  },
  575: { timezone: "America/Denver", offset: "MTN", region: "New Mexico" },
  579: { timezone: "America/Montreal", offset: "EST", region: "Quebec" },
  580: { timezone: "America/Chicago", offset: "CEN", region: "Oklahoma" },
  581: { timezone: "America/Montreal", offset: "EST", region: "Quebec" },
  585: { timezone: "America/New_York", offset: "EST", region: "New York" },
  606: { timezone: "America/New_York", offset: "EST", region: "Kentucky" },
  607: { timezone: "America/New_York", offset: "EST", region: "New York" },
  608: { timezone: "America/Chicago", offset: "CEN", region: "Wisconsin" },
  609: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  610: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  612: { timezone: "America/Chicago", offset: "CEN", region: "Minnesota" },
  613: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  614: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  615: { timezone: "America/Chicago", offset: "CEN", region: "Tennessee" },
  616: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  617: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  618: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  619: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  620: { timezone: "America/Chicago", offset: "CEN", region: "Kansas" },
  623: { timezone: "America/Phoenix", offset: "MTN", region: "Arizona" },
  640: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  641: { timezone: "America/Chicago", offset: "CEN", region: "Iowa" },
  646: { timezone: "America/New_York", offset: "EST", region: "New York" },
  647: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  650: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  651: { timezone: "America/Chicago", offset: "CEN", region: "Minnesota" },
  657: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  659: { timezone: "America/Chicago", offset: "CEN", region: "Alabama" },
  660: { timezone: "America/Chicago", offset: "CEN", region: "Missouri" },
  661: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  662: { timezone: "America/Chicago", offset: "CEN", region: "Mississippi" },
  667: { timezone: "America/New_York", offset: "EST", region: "Maryland" },
  669: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  672: {
    timezone: "America/Vancouver",
    offset: "PAC",
    region: "British Columbia",
  },
  678: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  680: { timezone: "America/New_York", offset: "EST", region: "New York" },
  681: { timezone: "America/New_York", offset: "EST", region: "West Virginia" },
  682: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  689: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  701: { timezone: "America/Chicago", offset: "CEN", region: "North Dakota" },
  702: { timezone: "America/Los_Angeles", offset: "PAC", region: "Nevada" },
  703: { timezone: "America/New_York", offset: "EST", region: "Virginia" },
  704: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  705: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  706: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  707: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  708: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  709: {
    timezone: "America/St_Johns",
    offset: "NFI",
    region: "Newfoundland and Labrador",
  },
  712: { timezone: "America/Chicago", offset: "CEN", region: "Iowa" },
  714: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  715: { timezone: "America/Chicago", offset: "CEN", region: "Wisconsin" },
  716: { timezone: "America/New_York", offset: "EST", region: "New York" },
  717: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  718: { timezone: "America/New_York", offset: "EST", region: "New York" },
  719: { timezone: "America/Denver", offset: "MTN", region: "Colorado" },
  724: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  725: { timezone: "America/Los_Angeles", offset: "PAC", region: "Nevada" },
  726: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  727: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  731: { timezone: "America/Chicago", offset: "CEN", region: "Tennessee" },
  732: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  734: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  737: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  740: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  743: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  747: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  754: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  757: { timezone: "America/New_York", offset: "EST", region: "Virginia" },
  760: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  763: { timezone: "America/Chicago", offset: "CEN", region: "Minnesota" },
  765: {
    timezone: "America/Indiana/Indianapolis",
    offset: "EST",
    region: "Indiana",
  },
  769: { timezone: "America/Chicago", offset: "CEN", region: "Mississippi" },
  770: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  772: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  773: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  774: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  775: { timezone: "America/Los_Angeles", offset: "PAC", region: "Nevada" },
  778: {
    timezone: "America/Vancouver",
    offset: "PAC",
    region: "British Columbia",
  },
  779: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  780: { timezone: "America/Calgary", offset: "MTN", region: "Alberta" },
  781: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  782: { timezone: "America/Halifax", offset: "ATL", region: "Nova Scotia" },
  785: { timezone: "America/Chicago", offset: "CEN", region: "Kansas" },
  786: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  801: { timezone: "America/Denver", offset: "MTN", region: "Utah" },
  802: { timezone: "America/New_York", offset: "EST", region: "Vermont" },
  803: {
    timezone: "America/New_York",
    offset: "EST",
    region: "South Carolina",
  },
  804: { timezone: "America/New_York", offset: "EST", region: "Virginia" },
  805: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  806: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  807: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  808: { timezone: "Pacific/Honolulu", offset: "HAW", region: "Hawaii" },
  809: {
    timezone: "America/Santo_Domingo",
    offset: "AST",
    region: "Dominican Republic",
  },
  810: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  812: {
    timezone: "America/Indiana/Indianapolis",
    offset: "EST",
    region: "Indiana",
  },
  813: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  814: { timezone: "America/New_York", offset: "EST", region: "Pennsylvania" },
  817: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  818: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  819: { timezone: "America/Montreal", offset: "EST", region: "Quebec" },
  820: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  825: { timezone: "America/Calgary", offset: "MTN", region: "Alberta" },
  828: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  830: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  831: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  832: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  838: { timezone: "America/New_York", offset: "EST", region: "New York" },
  843: {
    timezone: "America/New_York",
    offset: "EST",
    region: "South Carolina",
  },
  847: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  848: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  850: { timezone: "America/Chicago", offset: "CEN", region: "Florida" },
  854: {
    timezone: "America/New_York",
    offset: "EST",
    region: "South Carolina",
  },
  856: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  857: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  858: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  859: { timezone: "America/Louisville", offset: "EST", region: "Kentucky" },
  860: { timezone: "America/New_York", offset: "EST", region: "Connecticut" },
  862: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  863: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  864: {
    timezone: "America/New_York",
    offset: "EST",
    region: "South Carolina",
  },
  865: { timezone: "America/New_York", offset: "EST", region: "Tennessee" },
  867: { timezone: "America/Whitehorse", offset: "PAC", region: "Yukon" },
  870: { timezone: "America/Chicago", offset: "CEN", region: "Arkansas" },
  872: { timezone: "America/Chicago", offset: "CEN", region: "Illinois" },
  877: { timezone: "America/New_York", offset: "EST", region: "Canada" },
  901: { timezone: "America/Chicago", offset: "CEN", region: "Tennessee" },
  902: { timezone: "America/Halifax", offset: "ATL", region: "Nova Scotia" },
  903: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  904: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  905: { timezone: "America/Toronto", offset: "EST", region: "Ontario" },
  906: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  907: { timezone: "America/Anchorage", offset: "ALA", region: "Alaska" },
  908: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  909: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  910: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  912: { timezone: "America/New_York", offset: "EST", region: "Georgia" },
  913: { timezone: "America/Chicago", offset: "CEN", region: "Kansas" },
  914: { timezone: "America/New_York", offset: "EST", region: "New York" },
  928: { timezone: "America/Phoenix", offset: "MTN", region: "Arizona" },
  929: { timezone: "America/New_York", offset: "EST", region: "New York" },
  930: {
    timezone: "America/Indiana/Indianapolis",
    offset: "EST",
    region: "Indiana",
  },
  931: { timezone: "America/Chicago", offset: "CEN", region: "Tennessee" },
  934: { timezone: "America/New_York", offset: "EST", region: "New York" },
  936: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  937: { timezone: "America/New_York", offset: "EST", region: "Ohio" },
  938: { timezone: "America/Chicago", offset: "CEN", region: "Alabama" },
  940: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  941: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  947: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
  949: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  951: { timezone: "America/Los_Angeles", offset: "PAC", region: "California" },
  952: { timezone: "America/Chicago", offset: "CEN", region: "Minnesota" },
  954: { timezone: "America/New_York", offset: "EST", region: "Florida" },
  956: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  959: { timezone: "America/New_York", offset: "EST", region: "Connecticut" },
  970: { timezone: "America/Denver", offset: "MTN", region: "Colorado" },
  971: { timezone: "America/Los_Angeles", offset: "PAC", region: "Oregon" },
  972: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  973: { timezone: "America/New_York", offset: "EST", region: "New Jersey" },
  978: { timezone: "America/New_York", offset: "EST", region: "Massachusetts" },
  979: { timezone: "America/Chicago", offset: "CEN", region: "Texas" },
  980: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  984: {
    timezone: "America/New_York",
    offset: "EST",
    region: "North Carolina",
  },
  985: { timezone: "America/Chicago", offset: "CEN", region: "Louisiana" },
  986: { timezone: "America/Boise", offset: "MTN", region: "Idaho" },
  989: { timezone: "America/Detroit", offset: "EST", region: "Michigan" },
};

app.get("/timezone", (req, res) => {
  const areaCode = req.query.areaCode;
  if (!areaCode || typeof areaCode !== "string" || areaCode.length !== 3) {
    return res.status(400).json({
      error: "Please provide a valid 3-digit areaCode as a query parameter.",
    });
  }
  const areaCodeData = timezoneMap[areaCode] || {
    timezone: "Unknown",
    offset: "Unknown",
    region: "Unknown",
  };
  return res.json({
    areaCode,
    timezone: areaCodeData.timezone,
    offset: areaCodeData.offset,
    region: areaCodeData.region,
  });
});

app.get("/", (req, res) => {
  res.send("Timezone API is running. Use /timezone?areaCode=XXX");
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
